import 'package:flutter/material.dart';
import 'package:login/pages/bookmodel.dart';

var categorydata  = [

  {
    "Icon":"assets/icons/heart.svg",
    "lebal":"Programming"
  },
  {
    "Icon":"assets/icons/heart.svg",
    "lebal":"Computer Science"
  },
  {
    "Icon":"assets/icons/heart.svg",
    "lebal":"Information technology"
  },
  {
    "Icon":"assets/icons/heart.svg",
    "lebal":"Machine learning"
  }
];

var bookdata1 = [
  Bookmodel(
    id: "1",
    title: "STARTING WITH PYTHON",
    description: "The book typically covers fundamental programming concepts using Python as the primary language for instruction. ",
    aboutAuthor: "hi my name is Tony Gaddis and i have written this book",
    audioLen: "20",
    author: "Tony Gaddis",
    coverUrl: "assets/img/python.jpg",
    rating: "4.2",
    category: "Education",
    numberofRating: "10",
    pages: 625,
    language: "ENG",
    bookurl: "https://www.kalfaoglu.com/ceng113/Python-Programming/Starting%20Out%20with%20Python%5B4th%20Globa%20lED%5DTony%20Gaddis.pdf",
  ),
  Bookmodel(
    id: "2",
    title: "LEARN PYTHON THE HARD WAY",
    description: "The book typically covers fundamental programming concepts using Python as the primary language for instruction. ",
    aboutAuthor: "hi my name is Zed A. Shaw and i have written this book",
    audioLen: "20",
    author: "Zed A. Shaw",
    coverUrl: "assets/img/LEARN PYTHON BY HARD WAY.jpg",
    rating: "4.2",
    category: "Education",
    numberofRating: "10",
    pages: 306,
    language: "ENG",
    bookurl: "https://www.cs.cmu.edu/~srini/15-441/F11/LPTHW/lpthw.pdf",
  ),
  Bookmodel(
    id: "3",
    title: "Expert Python Programming",
    description: "The book typically covers fundamental programming concepts using Python as the primary language for instruction. ",
    aboutAuthor: "hi my name is Tarek Ziadé and i have written this book",
    audioLen: "20",
    author: "Tarek Ziadé",
    coverUrl: "assets/img/Expert Python Programming.jpg",
    rating: "4.2",
    category: "Education",
    numberofRating: "10",
    pages: 370,
    language: "ENG",
    bookurl: "https://edu.anarcho-copy.org/Programming%20Languages/Python/Expert%20Python%20Programming%20-%20Third%20Edition.pdf",
  ),
  Bookmodel(
      id: "4",
      title: "programming  python",
      description: "The book typically covers fundamental programming concepts using Python as the primary language for instruction. ",
      aboutAuthor: "hi my name is Hans-Petter Halvorsen and i have written this book",
      audioLen: "20",
      author: "Hans-Petter Halvorsen",
      coverUrl: "assets/img/programming with python.jpg",
      rating: "4.2",
      category: "Education",
      numberofRating: "10",
      pages: 349,
      language: "ENG",
      bookurl: "https://www.halvorsen.blog/documents/programming/python/resources/Python%20Programming.pdf"
  ),
];

var bookdata2 = [
  Bookmodel(
    id: "1",
    title: "C++ DATA STRUCTURE",
    description: "The book typically covers fundamental programming concepts using C++ as the primary language for instruction. ",
    aboutAuthor: "hi my name is Mark Allen Weiss and i have written this book",
    audioLen: "20",
    author: "Mark Allen Weiss",
    coverUrl: "assets/img/img_1.png",
    rating: "4.2",
    category: "Education",
    numberofRating: "10",
    pages: 654,
    language: "ENG",
    bookurl: "https://www.uoitc.edu.iq/images/documents/informatics-institute/Competitive_exam/DataStructures.pdf",
  ),
  Bookmodel(
    id: "2",
    title: "C++ PROGRAMMING",
    description: "The book typically covers fundamental programming concepts using C++ as the primary language for instruction. ",
    aboutAuthor: "hi my name is Richard Grimes and i have written this book",
    audioLen: "20",
    author: "Richard Grimes",
    coverUrl: "assets/img/img_2.png",
    rating: "4.2",
    category: "Education",
    numberofRating: "10",
    pages: 516,
    language: "ENG",
    bookurl: "https://notalentgeek.github.io/note/note/project/project-independent/pi-brp-beginning-c-programming/document/20170807-1504-cet-1-book-and-source-1.pdf",
  ),
  Bookmodel(
    id: "3",
    title: "OBJECT ORIENTED PROGRAMMING",
    description: "The book typically covers fundamental programming concepts using C++ as the primary language for instruction. ",
    aboutAuthor: "hi my name is Robert Lafore and i have written this book",
    audioLen: "20",
    author: "Robert Lafore",
    coverUrl: "assets/img/img_3.png",
    rating: "4.2",
    category: "Education",
    numberofRating: "10",
    pages: 1038,
    language: "ENG",
    bookurl: "https://faculty.ksu.edu.sa/sites/default/files/ObjectOrientedProgramminginC4thEdition.pdf",
  ),
  Bookmodel(
      id: "4",
      title: "LEARN C++",
      description: "The book typically covers fundamental programming concepts using C++ as the primary language for instruction. ",
      aboutAuthor: "hi my name is Herbert Schildt and i have written this book",
      audioLen: "20",
      author: "Herbert Schildt",
      coverUrl: "assets/img/img_4.png",
      rating: "4.2",
      category: "Education",
      numberofRating: "10",
      pages: 541,
      language: "ENG",
      bookurl: "https://www.micc.unifi.it/bertini/download/labtecinf/C%2B%2B%20A%20Beginner%27s%20Guide%202nd%20Edition%20(2003).pdf"
  ),
];

var bookdata3 = [
  Bookmodel(
    id: "1",
    title: "PYTHON MACHINE LEARNING",
    description: "The book typically covers fundamental programming concepts using Machine learning as the primary language for instruction. ",
    aboutAuthor: "hi my name is Sebastian Raschka and i have written this book",
    audioLen: "20",
    author: "Sebastian Raschka",
    coverUrl: "assets/img/img_5.png",
    rating: "4.2",
    category: "Education",
    numberofRating: "10",
    pages: 622,
    language: "ENG",
    bookurl: "http://radio.eng.niigata-u.ac.jp/wp/wp-content/uploads/2020/06/python-machine-learning-2nd.pdf",
  ),
  Bookmodel(
    id: "2",
    title: "MACHINE LEARNING",
    description: "The book typically covers fundamental programming concepts using Machine learning as the primary language for instruction. ",
    aboutAuthor: "hi my name is  Tom Mitchell and i have written this book",
    audioLen: "20",
    author: " Tom Mitchell",
    coverUrl: "assets/img/img_6.png",
    rating: "4.2",
    category: "Education",
    numberofRating: "10",
    pages: 421,
    language: "ENG",
    bookurl: "https://www.cin.ufpe.br/~cavmj/Machine%20-%20Learning%20-%20Tom%20Mitchell.pdf",
  ),
  Bookmodel(
    id: "3",
    title: "DEEP LEARNING WITH PYTHON",
    description: "The book typically covers fundamental programming concepts using deep learning as the primary language for instruction. ",
    aboutAuthor: "hi my name is François Chollet and i have written this book",
    audioLen: "20",
    author: "François Chollet",
    coverUrl: "assets/img/img_7.png",
    rating: "4.2",
    category: "Education",
    numberofRating: "10",
    pages: 386,
    language: "ENG",
    bookurl: "https://tanthiamhuat.wordpress.com/wp-content/uploads/2018/03/deeplearningwithpython.pdf",
  ),
  Bookmodel(
      id: "4",
      title: "Deep Learning for Coders ",
      description: "The book typically covers fundamental programming concepts using DEEP learning as the primary language for instruction. ",
      aboutAuthor: "hi my name is Jeremy Howard  and i have written this book",
      audioLen: "20",
      author: "Jeremy Howard ",
      coverUrl: "assets/img/img_8.png",
      rating: "4.2",
      category: "Education",
      numberofRating: "10",
      pages: 622,
      language: "ENG",
      bookurl: "https://dl.ebooksworld.ir/books/Deep.Learning.for.Coders.with.fastai.and.PyTorch.Howard.Gugger.OReilly.9781492045526.EBooksWorld.ir.pdf"
  ),
];